name: workflow-maven-package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout.
        uses: actions/checkout@v2

      - name: Step 2 - Setup Java.
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Step 3 - Maven Package.
        run: mvn -B package

      - name: Step 4 - CodeCov.
        uses: codecov/codecov-action@v1