name: "workflow-maven-install"

on:
  push:
    branches-ignore:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-SNAPSHOT"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Step 1 - Checkout."
        uses: "actions/checkout@v3"

      - name: "Step 2 - Setup Java."
        uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "11"
          server-id: "ossrh"
          server-username: "SERVER_USERNAME"
          server-password: "SERVER_PASSWORD"

      - name: "Step 3 - Maven Install."
        run: "mvn -B install -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=error -Dgpg.skip"
        env:
          SERVER_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
          SERVER_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"